@API_HostAddress = http://localhost:5185/api

post {{API_HostAddress}}/accounts/login/
Content-Type: application/json
{
  "UserName": "dragan",
  "Password": "1234"
}
###

POST {{API_HostAddress}}/accounts/register
Content-Type: application/json
{
  "UserName": "dragan",
  "Email": "opric.dragan@gmail.com",
  "Password": "test1234"
}

###
